name: Ubuntu 20.04

on:
  push:
    branches:
      - openssl-3.0.15-compilation

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: |
          ./config
          make
          make test
          make install